version: '2.1'
services:

  config-server:
    build: config-server
    ports:
      - 8710:8710
    #environment:
      #- EUREKA_SERVICE_URL:
      #- CONFIG_FILES_DIR:
    links:
      - eureka-server

  eureka-server:
    build: eureka-server
    ports:
      - 8700:8700

  user-service:
    build: user-service
    ports:
      - 8720:8720
    links:
      - config-server
    # environment:
    #   - CONFIG_SERVER_URL:''

  node-sidecar:
    build: node-sidecar
    ports:
      - 8741:8741
    links:
      - config-server
      - book-service-by-node
    # environment:
    #   - CONFIG_SERVER_URL:''

  book-service-by-node:
    build: book-service-by-node
    ports:
      - 3000:3000

  monitoring:
    build: monitoring
    ports:
      - 8080:8080
      - 8989:8989
    links:
      - config-server
    # environment:
    #   - CONFIG_SERVER_URL:''