version: '2.1'
services:

  # config-server:
  #   build: config-server
  #   ports:
  #     - 8710:8710
    #environment:
      #- EUREKA_SERVICE_URL=
      #- CONFIG_FILES_DIR=
    # links:
    #   - eureka-server

  eureka-server:
    build: eureka-server
    ports:
      - 8700:8700

  user-service:
    build: user-service
    ports:
      - 8720:8720
    links:
      - eureka-server
    environment:
      - HOST_IP=172.17.0.1
      - EUREKA_SERVICE_URL=http://172.17.0.1:8700/eureka/

  node-sidecar:
    build: node-sidecar
    ports:
      - 8741:8741
    links:
      - eureka-server
      - book-service-by-node
    environment:
      - HOST_IP=172.17.0.1
      - EUREKA_SERVICE_URL=http://172.17.0.1:8700/eureka/

  book-service-by-node:
    build: book-service-by-node
    ports:
      - 3000:3000
    environment:
      - HOST_IP=172.17.0.1

  # monitoring:
  #   build: monitoring
  #   ports:
  #     - 8080:8080
  #     - 8989:8989
  #   links:
  #     - eureka-server
    # environment:
    #   - CONFIG_SERVER_URL=