server:
  port: 8710

# spring:
#   application:
#     name: config-server
#   cloud:
#     config:
#       server:
#         git:
#           uri: https://github.com/marshalYuan/spring-cloud-example/
#           searchPaths: config-repo
#           username:
#           password:

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8700/eureka/
    fetchRegistry: true
    registerWithEureka: true